FROM python:3.10-slim
RUN apt-get update 
RUN apt -y install build-essential

RUN apt-get update 

RUN pip install pytest pytest-watch pytest-testmon
RUN pip install matplotlib pandas scikit-learn

RUN mkdir /src
WORKDIR /src
