FROM python:3.10-slim

RUN apt-get update 
RUN apt -y install build-essential

RUN pip3 install --upgrade pip

RUN pip3 install -U pylint
RUN pip3 install pandas sklearn
RUN pip3 install pytest matplotlib

RUN mkdir /src
WORKDIR /src
ENTRYPOINT ["pylint"]
