FROM python:3.11-slim
RUN apt-get update && \
    apt upgrade -y && \
    apt -y install build-essential vim && \
    pip3 install --upgrade pip && \
    mkdir /code
RUN echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
RUN apt install -y graphviz font-manager

RUN pip install --upgrade pip
RUN pip install \
    matplotlib pandas scikit-learn \
    graphviz ipython

WORKDIR /code
