name: build
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: sudo apt install -y graphviz
      - run: python3 --version
      - run: pip3 install --upgrade pip 
      - run: pip3 install -e .
      - run: pip3 install pytest
      - run: python3 -m pytest -p no:cacheprovider
      - run: pip3 install ipython
      - run: python3 -m pytest -p no:cacheprovider

  ruff:
    runs-on: ubuntu-latest
    name: Run ruff
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip3 install ruff
      - name: Run ruff
        run: python3 -m ruff dmba

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip3 install -U pip mypy 
        # types-Deprecated types-PyYAML types-requests types-simplejson isort types-pytz types-python-dateutil types-orjson
      
      - name: Run mypy cdd
        run: python3 -m mypy dmba
