name: dmba-tests
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
on: [push]
jobs:
  python-tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: make images
      - run: make tests
